/**
 * Provenance Audit Trail Component
 * 
 * Displays comprehensive audit trail of all document modifications.
 */

'use client';

import React, { useMemo } from 'react';

import type { ParagraphProvenance } from '@/lib/provenance/types';

interface AuditTrailEntry {
  timestamp: Date;
  action: string;
  details: string;
  severity: 'info' | 'warning' | 'success';
  metadata?: Record<string, unknown>;
}

export interface ProvenanceAuditTrailProps {
  /** Paragraph-level provenance data */
  provenance: ParagraphProvenance[];
}

/**
 * Convert provenance to audit trail entries
 */
function convertToAuditTrail(provenance: ParagraphProvenance[]): AuditTrailEntry[] {
  const entries: AuditTrailEntry[] = [];

  for (const para of provenance) {
    for (const event of para.events) {
      if (!event.timestamp) continue;

      const baseEntry: AuditTrailEntry = {
        timestamp: new Date(event.timestamp),
        metadata: {
          paragraphId: para.paragraphId,
          contentPreview: (para.content ?? '').substring(0, 50),
        },
        severity: 'info',
        action: '',
        details: '',
      };

      switch (event.eventType) {
        case 'human-written':
          entries.push({
            ...baseEntry,
            action: 'Paragraph Written',
            details: `Human author created new paragraph`,
            severity: 'success',
          });
          break;

        case 'human-edit':
          entries.push({
            ...baseEntry,
            action: 'Paragraph Edited',
            details: `Human author made modifications`,
            severity: 'info',
          });
          break;

        case 'ai-generation':
          entries.push({
            ...baseEntry,
            action: 'AI Generation',
            details: `Generated by ${event.aiModel || 'AI'} with ${((event.confidence || 0) * 100).toFixed(0)}% confidence`,
            severity: 'info',
            metadata: {
              ...baseEntry.metadata,
              model: event.aiModel,
              provider: event.aiProvider,
              confidence: event.confidence,
              prompt: event.aiPrompt?.substring(0, 50),
            },
          });
          break;

        case 'ai-modification':
          entries.push({
            ...baseEntry,
            action: 'AI Modification',
            details: `Modified by ${event.aiModel || 'AI'} with ${((event.confidence || 0) * 100).toFixed(0)}% confidence`,
            severity: 'info',
            metadata: {
              ...baseEntry.metadata,
              model: event.aiModel,
              provider: event.aiProvider,
              confidence: event.confidence,
              prompt: event.aiPrompt?.substring(0, 50),
            },
          });
          break;
      }

      if (event.reviewedAt) {
        entries.push({
          timestamp: new Date(event.reviewedAt),
          action: 'Review Completed',
          details: `Reviewed by ${event.reviewedBy || 'user'}`,
          severity: 'success',
          metadata: {
            paragraphId: para.paragraphId,
            reviewedBy: event.reviewedBy,
          },
        });
      }
    }
  }

  // Sort by timestamp descending (newest first)
  return entries.sort((a, b) => b.timestamp.getTime() - a.timestamp.getTime());
}

/**
 * Get severity icon and color
 */
function getSeverityStyles(severity: AuditTrailEntry['severity']): {
  icon: string;
  bgColor: string;
  textColor: string;
  borderColor: string;
} {
  switch (severity) {
    case 'success':
      return {
        icon: '✓',
        bgColor: 'bg-green-50 dark:bg-green-900',
        textColor: 'text-green-700 dark:text-green-200',
        borderColor: 'border-green-200 dark:border-green-700',
      };
    case 'warning':
      return {
        icon: '⚠',
        bgColor: 'bg-yellow-50 dark:bg-yellow-900',
        textColor: 'text-yellow-700 dark:text-yellow-200',
        borderColor: 'border-yellow-200 dark:border-yellow-700',
      };
    default:
      return {
        icon: 'ℹ',
        bgColor: 'bg-blue-50 dark:bg-blue-900',
        textColor: 'text-blue-700 dark:text-blue-200',
        borderColor: 'border-blue-200 dark:border-blue-700',
      };
  }
}

/**
 * Provenance Audit Trail
 * Shows comprehensive audit history of all document changes
 */
export function ProvenanceAuditTrail({ provenance }: ProvenanceAuditTrailProps) {
  const auditTrail = useMemo(() => convertToAuditTrail(provenance), [provenance]);

  if (auditTrail.length === 0) {
    return (
      <div className="text-center py-12 text-gray-500 dark:text-gray-400">
        No audit trail entries found
      </div>
    );
  }

  // Summary statistics
  const stats = {
    total: auditTrail.length,
    humanWrites: auditTrail.filter(e => e.action === 'Paragraph Written').length,
    humanEdits: auditTrail.filter(e => e.action === 'Paragraph Edited').length,
    aiGenerations: auditTrail.filter(e => e.action === 'AI Generation').length,
    aiModifications: auditTrail.filter(e => e.action === 'AI Modification').length,
    reviews: auditTrail.filter(e => e.action === 'Review Completed').length,
  };

  return (
    <div className="space-y-6">
      {/* Summary stats */}
      <div className="grid grid-cols-2 md:grid-cols-6 gap-3">
        {Object.entries(stats).map(([key, value]) => (
          <div key={key} className="bg-gray-50 dark:bg-gray-800 p-3 rounded-lg border border-gray-200 dark:border-gray-700">
            <div className="text-xl font-bold text-gray-900 dark:text-gray-100">
              {value}
            </div>
            <div className="text-xs text-gray-600 dark:text-gray-400 capitalize">
              {key.replace(/([A-Z])/g, ' $1').trim()}
            </div>
          </div>
        ))}
      </div>

      {/* Audit entries table */}
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead>
            <tr className="border-b border-gray-200 dark:border-gray-700">
              <th className="text-left py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">
                Time
              </th>
              <th className="text-left py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">
                Action
              </th>
              <th className="text-left py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">
                Details
              </th>
              <th className="text-left py-3 px-4 font-semibold text-gray-700 dark:text-gray-300">
                Paragraph
              </th>
            </tr>
          </thead>
          <tbody>
            {auditTrail.map((entry, idx) => {
              const severity = getSeverityStyles(entry.severity);
              return (
                <tr
                  key={idx}
                  className={`border-b border-gray-100 dark:border-gray-800 hover:bg-gray-50 dark:hover:bg-gray-750 transition-colors ${entry.severity === 'warning' ? 'bg-yellow-50 dark:bg-yellow-900' : ''}`}
                >
                  <td className="py-3 px-4 text-gray-600 dark:text-gray-400">
                    {entry.timestamp.toLocaleString()}
                  </td>
                  <td className="py-3 px-4">
                    <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-full text-xs font-medium ${severity.bgColor} ${severity.textColor}`}>
                      <span>{severity.icon}</span>
                      {entry.action}
                    </span>
                  </td>
                  <td className="py-3 px-4 text-gray-600 dark:text-gray-400">
                    {entry.details}
                  </td>
                  <td className="py-3 px-4 text-gray-500 dark:text-gray-500 text-xs">
                    {typeof entry.metadata?.contentPreview === 'string'
                      ? `"${entry.metadata.contentPreview}..."`
                      : '—'}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Detailed view for each entry */}
      <div className="mt-8 space-y-4">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
          Detailed History
        </h3>
        {auditTrail.map((entry, idx) => {
          const severity = getSeverityStyles(entry.severity);
          return (
            <div
              key={idx}
              className={`border rounded-lg p-4 ${severity.borderColor} ${severity.bgColor}`}
            >
              <div className="flex items-start gap-3">
                <div className={`flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center ${entry.severity === 'success' ? 'bg-green-500' : entry.severity === 'warning' ? 'bg-yellow-500' : 'bg-blue-500'} text-white text-sm font-bold`}>
                  {severity.icon}
                </div>
                <div className="flex-1">
                  <div className="flex justify-between items-start mb-1">
                    <h4 className={`font-semibold ${severity.textColor}`}>
                      {entry.action}
                    </h4>
                    <span className="text-xs text-gray-600 dark:text-gray-400">
                      {entry.timestamp.toLocaleString()}
                    </span>
                  </div>
                  <p className="text-sm text-gray-700 dark:text-gray-300 mb-2">
                    {entry.details}
                  </p>
                  {entry.metadata && Object.keys(entry.metadata).length > 0 && (
                    <div className="text-xs text-gray-600 dark:text-gray-400 bg-white dark:bg-gray-800 p-2 rounded mt-2">
                      {Object.entries(entry.metadata).map(([key, value]) => (
                        <div key={key}>
                          <span className="font-medium">{key}:</span>{' '}
                          {typeof value === 'string' ? value : JSON.stringify(value)}
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
