package com.dictator.core.data.converter

import com.dictator.core.domain.entity.*
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

// The database row types are generated by SQLDelight from the .sq files. These aliases keep
// the converter signatures reading in domain terms (DbUser rather than Users) and are the
// single point where the generated names are referenced.
typealias DbAiSession = com.dictator.core.database.AiSessions
typealias DbDocument = com.dictator.core.database.Documents
typealias DbDocumentConflict = com.dictator.core.database.DocumentConflicts
typealias DbDocumentVersion = com.dictator.core.database.DocumentVersions
typealias DbFolder = com.dictator.core.database.Folders
typealias DbPendingSyncItem = com.dictator.core.database.PendingSyncQueue
typealias DbShare = com.dictator.core.database.Shares
typealias DbSyncMetadata = com.dictator.core.database.SyncMetadata
typealias DbUser = com.dictator.core.database.Users

/**
 * Entity converters for mapping between database DTOs and domain entities.
 * Handles JSON serialization/deserialization for complex fields.
 */

private val json = Json {
    ignoreUnknownKeys = true
    coerceInputValues = true
}

// ============= User Converters =============

fun DbUser.toDomainEntity(): User = User(
    id = id,
    email = email,
    name = name,
    createdAt = createdAt
)

// ============= Folder Converters =============

fun DbFolder.toDomainEntity(): Folder = Folder(
    id = id,
    name = name,
    userId = userId,
    parentId = parentId,
    createdAt = createdAt
)

// ============= Document Converters =============

fun DbDocument.toDomainEntity(): Document = Document(
    id = id,
    title = title,
    folderId = folderId,
    userId = userId,
    createdAt = createdAt,
    updatedAt = updatedAt,
    lastModifiedDevice = lastModifiedDevice,
    deviceVersion = deviceVersion
)

// ============= DocumentVersion Converters =============

fun DbDocumentVersion.toDomainEntity(): DocumentVersion = DocumentVersion(
    id = id,
    documentId = documentId,
    content = content,
    version = version,
    createdBy = createdBy,
    createdAt = createdAt,
    deviceSource = deviceSource,
    deviceVersion = deviceVersion
)

// ============= Share Converters =============

fun DbShare.toDomainEntity(): Share = Share(
    id = id,
    documentId = documentId,
    sharedWithUserId = sharedWithUserId,
    permission = permission,
    createdAt = createdAt
)

// ============= AiSession Converters =============

fun DbAiSession.toDomainEntity(): AiSession {
    val turns = try {
        // Parse JSON array of turns
        val turnsArray = json.decodeFromString<List<AiTurn>>("[$turnsJson]")
        turnsArray
    } catch (e: Exception) {
        emptyList()
    }
    
    val meta = metadata?.let { metaStr ->
        try {
            json.decodeFromString(metaStr)
        } catch (e: Exception) {
            null
        }
    }
    
    return AiSession(
        id = id,
        userId = userId,
        mode = mode,
        turns = turns,
        metadata = meta,
        createdAt = createdAt
    )
}

// ============= SyncMetadata Converters =============

fun DbSyncMetadata.toDomainEntity(): SyncMetadata = SyncMetadata(
    documentId = documentId,
    lastSyncedAt = lastSyncedAt,
    localVersion = localVersion,
    remoteVersion = remoteVersion,
    pendingChanges = pendingChanges,
    conflictStatus = conflictStatus,
    updatedAt = updatedAt
)

// ============= PendingSyncItem Converters =============

fun DbPendingSyncItem.toDomainEntity(): PendingSyncItem {
    val changeData = try {
        val jsonStr = "{$changeDataJson}"
        json.decodeFromString<Map<String, String>>(jsonStr)
    } catch (e: Exception) {
        emptyMap()
    }
    
    return PendingSyncItem(
        id = id,
        documentId = documentId,
        userId = userId,
        deviceId = deviceId,
        changeData = changeData,
        status = status,
        retryCount = retryCount,
        createdAt = createdAt,
        updatedAt = updatedAt
    )
}

// ============= DocumentConflict Converters =============

fun DbDocumentConflict.toDomainEntity(): DocumentConflict {
    return DocumentConflict(
        id = id,
        documentId = documentId,
        baseVersion = parseVersionJson(baseVersionJson),
        androidVersion = parseVersionJson(androidVersionJson),
        webVersion = parseVersionJson(webVersionJson),
        resolvedVersion = resolvedVersionJson?.let { parseVersionJson(it) },
        status = status,
        createdAt = createdAt,
        resolvedAt = resolvedAt
    )
}

private fun parseVersionJson(jsonStr: String): DocumentVersion {
    return try {
        kotlinx.serialization.json.Json.decodeFromString(jsonStr)
    } catch (e: Exception) {
        // Fallback to minimal version
        DocumentVersion(
            id = "unknown",
            documentId = "unknown",
            content = "",
            version = 0,
            createdAt = System.currentTimeMillis()
        )
    }
}

