/**
 * Document Provenance Page
 * 
 * Displays comprehensive provenance information for a document including:
 * - Paragraph-level edit history
 * - Timeline view of all modifications
 * - Audit trail
 * - C2PA manifest and signatures
 * - Export options with packaging strategies
 */

'use client';

import React, { useState } from 'react';

import { ExportDialog } from '@/components/provenance';
import {
  C2PAManifestViewer,
  type ExportOptions,
  ProvenanceViewer,
} from '@/components/provenance';

interface DocumentProvenancePageProps {
  params: {
    id: string;
  };
}

/**
 * Document Provenance Page
 * Shows all provenance information for a document
 */
export default function DocumentProvenancePage({ params }: DocumentProvenancePageProps) {
  const [showExportDialog, setShowExportDialog] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  // TODO: Fetch actual document provenance data
  // For now, showing placeholder state
  const documentId = params.id;
  const documentTitle = 'Sample Document';

  // Placeholder provenance data - would be fetched from API
  const provenanceData = [
    {
      paragraphId: '1',
      content: 'This is the first paragraph of the document.',
      events: [
        {
          eventType: 'human-written' as const,
          timestamp: new Date('2024-01-01').toISOString(),
        },
      ],
    },
    {
      paragraphId: '2',
      content: 'This paragraph was generated by AI.',
      events: [
        {
          eventType: 'ai-generation' as const,
          aiModel: 'Claude 3 Opus',
          aiProvider: 'Anthropic',
          confidence: 0.85,
          aiPrompt: 'Write a paragraph about AI in document editing',
          timestamp: new Date('2024-01-02').toISOString(),
        },
        {
          eventType: 'human-edit' as const,
          timestamp: new Date('2024-01-02T12:00:00').toISOString(),
          reviewedAt: new Date('2024-01-02T13:00:00').toISOString(),
          reviewedBy: 'john_doe',
        },
      ],
    },
  ];

  // Placeholder C2PA manifest
  const c2paManifest = {
    version: '1.0',
    createdAt: new Date().toISOString(),
    documentTitle,
    paragraphCount: provenanceData.length,
    aiContentPercentage: 0.5,
    signature: {
      algorithm: 'RSA-SHA256',
      timestamp: new Date().toISOString(),
      nonce: 'nonce-' + Math.random().toString(36).substr(2, 9),
      signature: 'MIIG...',
      verified: false,
    },
  };

  const handleExport = async (options: ExportOptions) => {
    setIsExporting(true);
    try {
      // Call export API endpoint
      const queryParams = new URLSearchParams({
        format: options.format,
        packaging: options.packaging,
        sign: String(options.sign),
        includeProvenance: String(options.includeProvenance),
        includeAuditTrail: String(options.includeAuditTrail),
        ...(options.compressData && { compressData: String(options.compressData) }),
      });

      const response = await fetch(
        `/api/documents/${documentId}/export-complete?${queryParams}`,
        {
          method: 'GET',
        }
      );

      if (!response.ok) {
        throw new Error('Export failed');
      }

      // Handle file download
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;

      // Determine filename based on format and packaging
      const fileExtensions: Record<typeof options.format, string> = {
        json: 'json',
        markdown: 'md',
        text: 'txt',
        html: 'html',
        pdf: 'pdf',
        csv: 'csv',
      };

      const extension = options.packaging === 'sidecar' ? 'zip' : fileExtensions[options.format];
      link.download = `document-${documentId}-export.${extension}`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      window.URL.revokeObjectURL(url);

      setShowExportDialog(false);
    } catch (error) {
      console.error('Export error:', error);
      alert('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <div className="container mx-auto py-8 px-4">
        {/* Navigation */}
        <div className="mb-6">
          <a
            href={`/documents/${documentId}`}
            className="text-blue-500 hover:text-blue-600 font-medium flex items-center gap-1"
          >
            ← Back to Document
          </a>
        </div>

        {/* Main Content */}
        <div className="space-y-8">
          {/* Provenance Viewer */}
          <ProvenanceViewer
            provenance={provenanceData}
            documentTitle={documentTitle}
            showAuditTrail={true}
            enableFiltering={true}
            onExport={() => setShowExportDialog(true)}
          />

          {/* C2PA Manifest */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow">
            <C2PAManifestViewer
              manifest={c2paManifest}
              showVerification={true}
              onVerify={async () => {
                // TODO: Implement actual signature verification
                return true;
              }}
            />
          </div>

          {/* Export Options Card */}
          <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 border-2 border-dashed border-gray-300 dark:border-gray-600">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-xl font-bold text-gray-900 dark:text-gray-100">
                  Export Document with Provenance
                </h3>
                <p className="text-gray-600 dark:text-gray-400 mt-1">
                  Export your document with complete provenance information, optional C2PA signing,
                  and flexible packaging strategies.
                </p>
              </div>
              <button
                onClick={() => setShowExportDialog(true)}
                className="px-8 py-3 bg-green-500 hover:bg-green-600 text-white rounded-lg font-bold transition-colors"
              >
                Export Now
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* Export Dialog */}
      {showExportDialog && (
        <ExportDialog
          onExport={handleExport}
          onClose={() => setShowExportDialog(false)}
          isLoading={isExporting}
          signingAvailable={true}
        />
      )}
    </div>
  );
}
